question: "Install Google Chrome browser?"
steps:
  - Downloading Google Chrome browser:
    - wget wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - Installing Google Chrome browser:
    - sudo apt install /tmp/chrome.deb

  - Cleanup downloaded files:
    - rm -f /tmp/chrome.deb
