question: "Install Micro text editor?"
steps:
  - Install dependencies:
    - sudo apt update
    - sudo apt install wget -y

  - Downloading install script:
    - wget -O /tmp/micro.sh https://getmic.ro

  - Installing Micro text editor:
    - sudo chmod +x /tmp/micro.sh
    - sudo /tmp/micro.sh
    - sudo mv ./micro /usr/bin/micro

  - Cleanup downloaded files:
    - rm -f /tmp/micro.sh
